apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do echo 'Hello from Busybox'; sleep 5; done"]
